"""create users table

Revision ID: e25acea7e9e4
Revises: 
Create Date: 2026-07-08 11:50:40.653132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e25acea7e9e4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crypto_data_id'), table_name='crypto_data')
    op.drop_index(op.f('ix_crypto_data_symbol'), table_name='crypto_data')
    op.drop_table('crypto_data')
    op.drop_index(op.f('ix_stock_data_id'), table_name='stock_data')
    op.drop_index(op.f('ix_stock_data_symbol'), table_name='stock_data')
    op.drop_table('stock_data')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('stock_data_pkey'))
    )
    op.create_index(op.f('ix_stock_data_symbol'), 'stock_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_stock_data_id'), 'stock_data', ['id'], unique=False)
    op.create_table('crypto_data',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('currency', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('crypto_data_pkey'))
    )
    op.create_index(op.f('ix_crypto_data_symbol'), 'crypto_data', ['symbol'], unique=False)
    op.create_index(op.f('ix_crypto_data_id'), 'crypto_data', ['id'], unique=False)
    # ### end Alembic commands ###
